# Checkpoints

**CP1**:
Given the list $[A, B, C]$, use the `itertools` module to generate all possible
combinations of 2 elements.

**Expected Output**:
$$
 (A, B) \\
 (A, C) \\
 (B, C)
$$

In [ ]:
import itertools
given_list = ['A', 'B', 'C']
comb = list(itertools.combinations(given_list, 2))
for c in comb:
    print(c)

('A', 'B')
('A', 'C')
('B', 'C')


**CP2**:
Use the `itertools` module to create a sequence that cycles through
['Python', 'is', 'fun'] infinitely. Print the first 10 elements of the sequence.

**Expected Output**:
$$
Python \\
is\\
fun\\
Python\\
is\\
fun\\
Python\\
is\\
fun\\
Python
$$

In [ ]:
import itertools
input = ['Python', 'is', 'fun']
ever_loop = itertools.cycle(input)
for i, e in enumerate(itertools.islice(ever_loop, 10)):
    print(e)
    if i == 9:
        break

Python
is
fun
Python
is
fun
Python
is
fun
Python


**CP3**:
Use the `glob` module to list all python (.py) files in your current working directory.




In [ ]:
import glob
files = glob.glob('*.py')
print(files)


[]


**CP4**: You are given the following HTML content below. Write a function that uses BeautifulSoup to parse the HTML and extract the text inside the   '$<p>$'   tag.


In [ ]:
#<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>

In [ ]:
from bs4 import BeautifulSoup
markup = "<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>"
soup = BeautifulSoup(markup, "html.parser")
print(soup.find("p").string)
print(soup.string)


AI is transforming the world
None


**CP5**: Write a function that uses the re module to replace all occurrences of the word "AI" with "Artificial Intelligence" in a given text.

In [ ]:
import re
pattern = r'\bAI\b'
replaced = re.sub(pattern, 'Artificial Intelligence', markup)
replaced

"<html><body><div class='main'><h1>Welcome to Artificial Intelligence</h1><p>Artificial Intelligence is transforming the world</p></div></body></html>"

**CP6**: Create a numpy array of 10 zeros.

In [ ]:
import numpy as np
array = np.zeros(10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**CP7** Create a numpy array of the integers from 10 to 49.

In [ ]:
range_array = np.arange(10, 50)
range_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**CP8**: Create a 3x3 numpy matrix, filled with values ranging from 0 to 8.

In [ ]:
array2 = np.arange(9).reshape(3,3)
array2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**CP9**: Explain why machine learning models require large amounts of data? What does it mean for an amount of data to be **large**?

In [ ]:
'''Machine Learning models require a large amount of training and testing data.
These large amount of data is used in making the model be more accurate.
 Specifically more data usually means more accurate generalizations and reduced
 noise effects on the model as well as a model that doesnot overfit the data.
  So large data is useful in enabling a model to be
 more accurate. The other one is more data means more complex models. The training
 algorithm will be able to catch a lot of complex connections and patterns more in
 a large data.

 What we mean when we say large amout of data is enough amount of data to train a model
 with the right accuracy measures.
'''

'Machine Learning models require a large amount of training and testing data. \nThese large amount of data is used in making the model be more accurate.\n Specifically more data usually means more accurate generalizations and reduced\n noise effects on the model. So large data is useful in enabling a model to be \n more accurate. The other one is more data means more complex models. The training \n algorithm will be able to catch a lot of complex connections and patterns more in \n'

**CP10**: Explain 2 ways AI can be used in an adverserial way, and what can be done to prevent it.

In [ ]:
'''One of the ways AI can be used in a negative manner is in Classification,
Biased classification or recognition of people and items. We can prevent this by
representing all groups in an relevant manner to help the model training process.
Other solution is to be able to setup a way to resolve this mistakes that the AI makes.

Another negative impact of an AI can be security attacks. AI bots and other systems
can launch software engineering and other attacks.

'''